#!/usr/bin/env bash

export DEV_ENV=$(cd "$(dirname "$0")" && pwd)
source "${DEV_ENV}/lib/log" && export -f log && export -f logp
source "${DEV_ENV}/lib/ansi-escapes"
source "${DEV_ENV}/lib/progress_bar" && export -f progress_bar

SRCS="${HOME}/src/upstream"

usage() {
    printf "${FG_L_MAGENTA}dev - Jayshozie's Autobuilder${COLOR_RESET}
Usage: ${FG_L_MAGENTA}dev ${FG_L_YELLOW}[-v|--verbose]
           [-h|[-]-help]
           [-d|[-]-dry-run]
           [-A|[-]-all]
           [-n|[-]-nvim|[-]-neovim]
           [-t|[-]-tmux]
           [-a|[-]-alacritty]
           [--license] ${COLOR_RESET}

Options:
  ${FG_L_YELLOW}-v  [-]-verbose             ${FG_L_BLUE}Runs commands loudly
  ${FG_L_YELLOW}-h  [-]-help                ${FG_L_BLUE}Shows this message
  ${FG_L_YELLOW}-d  [-]-dry-run             ${FG_L_BLUE}Doesn't run any commands, show what would be run instead
  ${FG_L_YELLOW}-A  [-]-all                 ${FG_L_BLUE}Build all programs
  ${FG_L_YELLOW}-n  [[-]-neovim|[-]-nvim]   ${FG_L_BLUE}Build Neovim
  ${FG_L_YELLOW}-t  [-]-tmux                ${FG_L_BLUE}Build tmux
  ${FG_L_YELLOW}-a  [-]-alacritty           ${FG_L_BLUE}Build Alacritty
  ${FG_L_YELLOW}--license                   ${FG_L_BLUE}Shows the program's license${COLOR_RESET}
"
}

license() {
    cat <<EOF
Copyright (C)  2026  Emir Baha YILDIRIM

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
EOF
}

run() {
    local cmd="$@"
    if [[ $DEV_DRY == '1' ]]; then
        LOG_DRY_RUN='1' logp 'DEV' "$cmd"
    elif [[ $DEV_VERBOSE == '1' ]]; then
        $cmd
    else
        $cmd > /dev/null 2>&1
    fi
}

################################################################################
################################# N E O V I M ##################################
################################################################################

NEOVIM_VERSION="v0.11.7"
TREESITTER_VERSION="v0.10.0"

build_neovim() {
    logp 'DEV' \
        "${FG_L_BLUE}Building Neovim...${COLOR_RESET}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 0 11
    sudo -v

    # source
    if [[ -d "${SRCS}/nvim-treesitter" ]]; then
        pushd "${SRCS}/nvim-treesitter" > /dev/null
        run 'git fetch'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 11
    else
        logp 'DEV' \
            "${FG_L_BLUE}Treesitter is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:nvim-treesitter/nvim-treesitter.git'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 11
        popd > /dev/null
        pushd "${SRCS}/nvim-treesitter"
    fi
    run "git checkout ${TREESITTER_VERSION}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 2 11
    popd > /dev/null

    if [[ ! -d "${SRCS}/neovim" ]]; then
        logp 'DEV' "${FG_L_BLUE}Neovim is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:neovim/neovim.git'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 3 11
        popd > /dev/null
        pushd "${SRCS}/neovim" > /dev/null
    else
        pushd "${SRCS}/neovim" > /dev/null
        run 'git fetch'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 3 11
    fi
    run "git checkout ${NEOVIM_VERSION}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 4 11

    # dependencies
    run 'sudo pacman -S base-devel cmake ninja curl git --noconfirm'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 5 11

    # build
    run 'git clean -dfx'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 6 11
    run 'make distclean'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 7 11
    run 'make CMAKE_BUILD_TYPE=RelWithDebInfo'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 8 11
    run 'sudo make install'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 9 11

    # why waste space
    run 'git clean -dfx'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 10 11
    run 'make distclean'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 11 11
    clean_progress_bar

    logp 'DEV' "${FG_L_GREEN}Neovim was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
################################### T M U X ####################################
################################################################################

TMUX_VERSION="3.6a"
TPM_VERSION="v3.1.0"

build_tmux() {
    logp 'DEV' \
        "${FG_L_BLUE}Building tmux...${COLOR_RESET}"
    sudo -v
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 0 10

    # source
    if [[ ! -d "${XDG_CONFIG_HOME}/tmux/plugins/tpm" ]]; then
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/" > /dev/null
        run 'git clone git@github:tmux-plugins/tpm.git'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 10
    else
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/tpm" > /dev/null
        run 'git fetch'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 10
    fi
    run "git checkout ${TPM_VERSION}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 2 10
    popd > /dev/null

    if [[ ! -d "${SRCS}/tmux" ]]; then
        logp 'DEV' "${FG_L_BLUE}tmux is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:tmux/tmux.git'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 3 10
        popd > /dev/null
        pushd "${SRCS}/tmux" > /dev/null
    else
        pushd "${SRCS}/tmux" > /dev/null
        run 'git fetch'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 3 10
    fi
    run "git checkout ${TMUX_VERSION}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 4 10

    # dependencies
    run 'sudo pacman -S libevent ncurses gcc automake autoconf pkg-config bison libutempter --noconfirm'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 5 10

    # build
    run 'git clean -dfx'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 6 10
    run 'sh autogen.sh'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 7 10
    run './configure' && run 'make'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 8 10
    run 'sudo make install'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 9 10

    # why waste space
    run 'git clean -dfx'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 10 10
    clean_progress_bar

    logp 'DEV' "${FG_L_GREEN}tmux was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
############################# A L A C R I T T Y ################################
################################################################################

ALACRITTY_VERSION="v0.17.0"

build_alacritty() {
    logp 'DEV' \
        "${FG_L_BLUE}Building Alacritty...${COLOR_RESET}"
    sudo -v
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 0 10

    # source
    if [[ ! -d "${SRCS}/alacritty" ]]; then
        logp 'DEV' \
            "${FG_L_BLUE}Alacritty is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:alacritty/alacritty.git'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 10
        popd > /dev/null
        pushd "${SRCS}/alacritty"
    else
        pushd "${SRCS}/alacritty" > /dev/null
        run 'git fetch'
        [[ $DEV_VERBOSE == '1' ]] || progress_bar 1 10
    fi
    run "git checkout ${ALACRITTY_VERSION}"
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 2 10

    # dependencies
    run 'sudo pacman -S rust cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python --noconfirm'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 3 10

    # build
    run 'cargo clean'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 4 10
    run 'cargo build --release --no-default-features --features=wayland'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 5 10

    # Install new binary (creates a NEW inode)
    run 'sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 6 10

    run 'sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 7 10
    run 'sudo desktop-file-install extra/linux/Alacritty.desktop'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 8 10
    run 'sudo update-desktop-database'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 9 10

    # why waste space
    run 'cargo clean'
    [[ $DEV_VERBOSE == '1' ]] || progress_bar 10 10
    clean_progress_bar

    logp 'DEV' "${FG_L_GREEN}Alacritty was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
#################################### A L L #####################################
################################################################################

build_all() {
    build_neovim
    build_tmux
    build_alacritty
}

################################################################################
################################### M A I N ####################################
################################################################################

sudo_msg() {
    logp 'DEV' \
        "${FG_L_YELLOW}This script requires sudo priveleges:${COLOR_RESET}"
}

main() {
    local short_flags='vhdDntaA'
    local long_flags='verbose,help,dry-run,license,neovim,nvim,tmux,alacritty,all'
    local flags=$(getopt -U -a -o ${short_flags} --long ${long_flags} -n ${0} -- ${@})
    [[ $DEV_DEBUG == '1' ]] && LOG_DEBUG='1' logp 'DEV' "args: [$flags]"
    eval set -- "$flags"
    while true; do
        case "$1" in
        '--')
            shift; break;;
        '-v'|'--verbose'|'-verbose')
            export DEV_VERBOSE='1'; shift; continue;;
        '-h'|'--help'|'-help')
            usage; exit 0;;
        '-d'|'-D'|'--dry-run'|'-dry-run')
            export DEV_DRY='1'; shift; continue;;
        '-l'|'--license'|'-license')
            license; exit 0;;
        '-n'|'--neovim'|'--nvim'|'-neovim'|'-nvim')
            sudo_msg; build_neovim; shift; continue;;
        '-t'|'--tmux'|'-tmux')
            sudo_msg; build_tmux; shift; continue;;
        '-a'|'--alacritty'|'-alacritty')
            sudo_msg; build_alacritty; shift; continue;;
        '-A'|'--all'|'-all')
            sudo_msg; build_all; shift; continue;;
        *) logp 'DEV' "${FG_L_RED}[ERR] Unknown option ${1}!${COLOR_RESET}" >&2
            usage >&2; exit 1;;
        esac
    done
}

main "$@"
