#!/usr/bin/env bash

export DEV_ENV=$(cd "$(dirname "$0")" && pwd)
source "${DEV_ENV}/lib/log" && export -f log && export -f logp
source "${DEV_ENV}/lib/ansi-escapes"

SRCS="${HOME}/src/upstream"

################################################################################
################################# N E O V I M ##################################
################################################################################

NEOVIM_VERSION="v0.12.2"
TREESITTER_VERSION="v0.10.0"

usage() {
    local prog_name="${0##*/}"
    cat <<EOF

$prog_name - Jayshozie's Autobuilder
Usage: $prog_name [-v|--verbose]
                  [-h|--help]
                  [-d|--dry-run]
                  [-l|--license]
                  [-n|--nvim|--neovim]
                  [-t|--tmux]
                  [-a|--alacritty]
                  [-A|--all]

Options:
  -v  --verbose           Shows extra info, runs all commands in verbose modes if applicable
  -h  --help              Shows this message
  -d  --dry-run           Doesn't run any commands, show what would've been run instead
  -l  --license           Shows the program's license
  -n  [--neovim|--nvim]   Build Neovim
  -t  --tmux              Build tmux
  -a  --alacritty         Build Alacritty
  -A  --all               Build all programs

EOF
}

license() {
    cat <<EOF

Copyright (C)  2026  Emir Baha YILDIRIM

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

EOF
}

run() {
    local cmd="$@"
    if [[ $DEV_DRY == '1' ]]; then
        LOG_DRY_RUN='1' logp 'DEV' "$cmd"
    elif [[ $DEV_VERBOSE == '1' ]]; then
        $cmd
    else
        $cmd > /dev/null 2>&1
    fi
}

build_neovim() {
    logp 'DEV' \
        "${FG_L_YELLOW}Building Neovim requires sudo priveleges:${COLOR_RESET}"
    sudo -v

    # source
    if [[ -d "${SRCS}/nvim-treesitter" ]]; then
        pushd "${SRCS}/nvim-treesitter" > /dev/null
        run 'git fetch'
    else
        logp 'DEV' \
            "${FG_L_BLUE}Treesitter is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:nvim-treesitter/nvim-treesitter.git'
        popd > /dev/null
        pushd "${SRCS}/nvim-treesitter"
    fi
    run "git checkout ${TREESITTER_VERSION}"
    popd > /dev/null

    if [[ ! -d "${SRCS}/neovim" ]]; then
        logp 'DEV' "${FG_L_BLUE}Neovim is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:neovim/neovim.git'
        popd > /dev/null
        pushd "${SRCS}/neovim" > /dev/null
    else
        pushd "${SRCS}/neovim" > /dev/null
        run 'git fetch'
    fi
    run "git checkout ${NEOVIM_VERSION}"

    # dependencies
    run 'sudo pacman -S base-devel cmake ninja curl git --noconfirm'

    # build
    run 'git clean -dfx'
    run 'make distclean'
    run 'make CMAKE_BUILD_TYPE=RelWithDebInfo'
    run 'sudo make install'

    # why waste space
    run 'git clean -dfx'
    run 'make distclean'

    logp 'DEV' "${FG_L_GREEN}Neovim was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
################################### T M U X ####################################
################################################################################

TMUX_VERSION="3.6a"
TPM_VERSION="v3.1.0"

build_tmux() {
    logp 'DEV' \
        "${FG_L_YELLOW}Building tmux requires sudo priveleges:${COLOR_RESET}"
    sudo -v

    # source
    if [[ ! -d "${XDG_CONFIG_HOME}/tmux/plugins/tpm" ]]; then
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/" > /dev/null
        run 'git clone git@github:tmux-plugins/tpm.git'
    else
        pushd "${XDG_CONFIG_HOME}/tmux/plugins/tpm" > /dev/null
        run 'git fetch'
    fi
    run "git checkout ${TPM_VERSION}"
    popd > /dev/null

    if [[ ! -d "${SRCS}/tmux" ]]; then
        logp 'DEV' "${FG_L_BLUE}tmux is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:tmux/tmux.git'
        popd > /dev/null
        pushd "${SRCS}/tmux" > /dev/null
    else
        pushd "${SRCS}/tmux" > /dev/null
        run 'git fetch'
    fi
    run "git checkout ${TMUX_VERSION}"

    # dependencies
    run 'sudo pacman -S libevent ncurses gcc automake autoconf pkg-config bison libutempter --noconfirm'

    # build
    run 'git clean -dfx'
    run 'sh autogen.sh'
    run './configure' && run 'make'
    run 'sudo make install'

    # why waste space
    run 'git clean -dfx'

    logp 'DEV' "${FG_L_GREEN}tmux was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
############################# A L A C R I T T Y ################################
################################################################################

ALACRITTY_VERSION="v0.16.1"

build_alacritty() {
    logp 'DEV' \
        "${FG_L_YELLOW}Building Alacritty requires sudo priveleges:${COLOR_RESET}"
    sudo -v

    # source
    if [[ ! -d "${SRCS}/alacritty" ]]; then
        logp 'DEV' \
            "${FG_L_BLUE}Alacritty is not cloned. Cloning...${COLOR_RESET}"
        pushd "$SRCS" > /dev/null
        run 'git clone git@github.com:alacritty/alacritty.git'
        popd > /dev/null
        pushd "${SRCS}/alacritty"
    else
        pushd "${SRCS}/alacritty" > /dev/null
        run 'git fetch'
    fi
    run "git checkout ${ALACRITTY_VERSION}"

    # dependencies
    run 'sudo pacman -S rust cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python --noconfirm'

    # build
    run 'cargo clean'
    run 'cargo build --release --no-default-features --features=wayland'

    # Install new binary (creates a NEW inode)
    run 'sudo install -m 755 target/release/alacritty /usr/local/bin/alacritty'

    run 'sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg'
    run 'sudo desktop-file-install extra/linux/Alacritty.desktop'
    run 'sudo update-desktop-database'

    # why waste space
    run 'cargo clean'

    logp 'DEV' "${FG_L_GREEN}Alacritty was built successfully! Don't forget to restart it!${COLOR_RESET}"

    popd > /dev/null
}

################################################################################
#################################### A L L #####################################
################################################################################

build_all() {
    build_neovim
    build_tmux
    build_alacritty
}

################################################################################
################################### M A I N ####################################
################################################################################

main() {
    local short_flags='vhdDlntaA'
    local long_flags='verbose,help,dry-run,license,neovim,nvim,tmux,alacritty,all'
    local flags=$(getopt -U -a -o ${short_flags} --long ${long_flags} -n ${0} -- ${@})
    [[ $DEV_DEBUG == '1' ]] && LOG_DEBUG='1' logp 'DEV' "args: [$flags]"
    eval set -- "$flags"
    while true; do
        case "$1" in
        '--')
            shift; break;;
        '-v'|'--verbose'|'-verbose')
            export DEV_VERBOSE='1'; shift; continue;;
        '-h'|'--help'|'-help')
            usage; exit 0;;
        '-d'|'-D'|'--dry-run'|'-dry-run')
            export DEV_DRY='1'; shift; continue;;
        '-l'|'--license'|'-license')
            license; exit 0;;
        '-n'|'--neovim'|'--nvim'|'-neovim'|'-nvim')
            build_neovim; shift; continue;;
        '-t'|'--tmux'|'-tmux')
            build_tmux; shift; continue;;
        '-a'|'--alacritty'|'-alacritty')
            build_alacritty; shift; continue;;
        '-A'|'--all'|'-all')
            build_all; shift; continue;;
        *) logp 'DEV' "${FG_L_RED}[ERR] Unknown option ${1}!${COLOR_RESET}" >&2
            usage >&2; exit 1;;
        esac
    done
}

main "$@"
