#!/usr/bin/env bash
# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

export DEV_ENV='/home/jaysh/dev'
source "${DEV_ENV}/lib/log" && export -f log
source "${DEV_ENV}/lib/progress_bar" && export -f progress_bar
source "${DEV_ENV}/lib/ansi-escapes"

help() {
    local prog_name="${0##*/}"
    cat <<EOF
$prog_name - AnyFlip PDF Creator/Downloader
Usage: $prog_name [-v|--verbose]
                  [-D|-d|--debug]
                  [-h|--help]
                  [-l|--license]

Options:
  -[d|D] --debug    Runs the script in debug mode and shows the debug messages
  -v     --verbose  Shows extra info, runs all commands in verbose modes if applicable
  -h     --help     Shows this message
  -l     --license  Shows the program's license
EOF
}

license() {
    cat <<EOF
Copyright (C)  2026  Emir Baha YILDIRIM

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
EOF
}

intro() {
    cat <<EOF
==================== AFPCD ====================
   Welcome to AnyFlip PDF Creator/Downloader
===============================================

Please make sure the link format is like this:
E.g.: https://online.anyflip.com/uxmrl/tnef/files/mobile/10.{jpg,webp}
EOF
}

outro() {
    cat <<EOF
           Thank you for using AFPCD!
==================== AFPCD ====================
EOF
}

clean_prog_bar() {
    printf '\e7'   # save the cursor location
    printf '\n'    # move cursor to the line below
    printf '\e[0K' # clear the line
    printf '\e8'   # restore the cursor location
}

check_link() {
    local link="$1"
    if [[ ! $link == 'https://online.anyflip.com/'*'/'* ]]; then
        logp 'AFPCD' "[ERROR] Invalid link! Please check the link you entered for errors: <${REPLY##*,}>"
        exit 1
    fi
}

check_pages() {
    local pages="$1"
    if [[ ! "$pages" =~ ^[0-9]+$ ]]; then
        logp 'AFPCD' "[ERROR] Please provide a valid integer. <$pages>"
        exit 1
    fi
}

check_location() {
    local location="$1"
    if [[ ! -d "$location" ]]; then
        logp 'AFPCD' "[ERROR] Directory [$location] not found!"
        exit 1
    fi
}

create_book() {
    local link total book_name location filetype payload down_link

    link="$1"
    total="$2"
    book_name="${3}.pdf"
    location="$4"
    filetype="$5"
    payload="/tmp/afpcd-book-${RANDOM}"

    mkdir "$payload"
    pushd "$payload" > /dev/null 2>&1

    link="${link}/files/mobile"

    wget_args='--tries=10'
    if [[ $AFPCD_VERBOSE != '1' ]]; then
        wget_args="${wget_args} -q"
    fi

    magick_args=()
    i=0
    for ((curr = 1; curr <= total; curr++)); do
        img_file="${curr}.${filetype}"
        magick_args[$i]="$img_file"
        ((i++))
        down_link="${link}/${img_file}"

        [[ $AFPCD_DEBUG == '1' ]] && LOG_DEBUG='1' \
            logp 'AFPCD' "[INFO] Will run: wget $wget_args $down_link"

        if ! wget $wget_args "$down_link"; then
            local reason="$?"
            logp 'AFPCD' "[ERROR] wget failed! [Exit Code: $reason]"
            popd > /dev/null 2>&1
            rm -rf "$payload"
            exit 1
        fi

        [[ $AFPCD_VERBOSE != '1' ]] && progress_bar "$curr" "$total"
        sleep .25
    done
    [[ $AFPCD_DEBUG == '1' ]] && LOG_DEBUG='1' \
        logp 'AFPCD' "[INFO] Download is complete. Constructing the PDF."

    if ! magick "${magick_args[@]}" "${book_name}"; then
        local reason="$?"
        logp 'AFPCD' "[ERROR] Magick failed! [Exit Code: $reason]"
        popd > /dev/null 2>&1
        rm -rf "$payload"
        exit 1
    fi
    [[ $AFPCD_DEBUG == '1' ]] && LOG_DEBUG='1' \
        logp 'AFPCD' "[INFO] PDF constructed. Located at <${payload}/${book_name}>"

    if ! cp "${payload}/${book_name}" "${location}/${book_name}"; then
        local reason="$?"
        logp 'AFPCD' "[ERROR] cp failed! [Exit Code: $reason]"
        logp 'AFPCD' "[WARN] You're highly recommended to copy the book to" \
            'somewhere else since it will be deleted after a reboot.' \
            "Book is located at <${payload}/${book_name}>."
        popd > /dev/null 2>&1
        exit 1
    fi

    popd > /dev/null 2>&1
    rm -rf "$payload"
}

main() {
    local short_flags='vhDdl'
    local long_flags='verbose,help,debug,license'
    local flags=$(getopt -o ${short_flags} --long ${long_flags} -n ${0} -- ${@})
    [[ "$AFPCD_DEBUG" == '1' ]] && LOG_DEBUG='1' logp 'AFPCD' "args: [$flags]"
    eval set -- "$flags"
    while true; do
        case "$1" in
        '--')
            shift
            break
            ;; # we have to assume that we're out of cli args
        '-v' | '--verbose')
            export AFPCD_VERBOSE='1'
            shift
            continue
            ;;
        '-d' | '-D' | '--debug')
            export AFPCD_DEBUG='1'
            shift
            continue
            ;;
        '-h' | '--help')
            help
            exit 0
            ;;
        '-l' | '--license')
            license
            exit 0
            ;;
        *) logp 'AFPCD' "[ERROR] Unknown option [$1]!" help exit 1 >&2 >&2 ;;
        esac
    done

    intro

    log 'Provide the AnyFlip Link: (e.g.: https://online.anyflip.com/uxmrl/tnef)'
    read -r link
    check_link $link

    log 'Provide the total amount of pages: (e.g.: 430)'
    read -r total_pages
    check_pages $total_pages

    log 'Provide the string to save the PDF as: (e.g.: v5-core-book)'
    read -r book_name

    log 'Provide the location on your PC to save the book (e.g.: /home/user/books)'
    read -r location
    check_location $location

    log 'Provide the filetype of the images that will be downloaded from AnyFlip: (e.g.: jpg, webp, png, etc.)'
    read -r filetype

    create_book $link $total_pages $book_name $location $filetype

    [[ $AFPCD_VERBOSE != '1' ]] && clean_prog_bar
    log "Your file is ready. It's stored at <$location/${book_name}.pdf>"

    outro
}

main "$@"
