#!/usr/bin/env bash
# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

log() {
    if [[ dry_run -eq 1 ]]; then
        printf "$timestamp [DRY]: $1\n" 2>&1
    else
        printf "$timestamp $1\n" 2>&1 | tee --append "${HOME}/die.log"
    fi
}

main() {
    dry_run=0

    if [[ $1 == "--dry-run" ]]; then
        dry_run=1
    fi

    log_file="${HOME}/die.log"

    if [[ ! -f $log_file ]]; then
        touch $log_file
    fi

    timestamp=$(date '+%Y/%m/%d %H:%M:%S')

    declare -A pids
    pids[nvim]=$(pgrep nvim -d ' ')
    pids[harper-ls]=$(pgrep harper-ls -d ' ')
    pids[librewolf]=$(pgrep librewolf -d ' ')
    pids[spotify]=$(pgrep spotify -d ' ')
    pids[jellyfin-deskto]=$(pgrep jellyfin-deskto -d ' ')

    status=0
    for p in "${!pids[@]}"; do
        if [[ "${pids[$p]}" == '' ]]; then
            log "[DIE] $p is not running."
            continue
        fi
        log "[DIE] SIGKILL $p --> ${pids[$p]}"
        if [[ dry_run -eq 1 ]]; then
            log "kill -9 ${pids[$p]}"
        else
            kill -9 ${pids[$p]}
        fi

        # if [[ dry_run -ne 1 && ! $(pgrep $p) ]]; then
        #     log "[DIE] Killed $p"
        # else
        #     log "[DIE] Couldn't kill ${p}."
        #     status=1
        # fi
    done

    if [[ status -ne 0 ]]; then
        log "[DIE] Couldn't kill all."
        log "[DIE] Please manually kill them, and then re-run the script."
    else
        log "[DIE] Killed everything successfully."
        log "[DIE] Shutting down ..."
        if [[ dry_run -eq 1 ]]; then
            log "shutdown now"
        else
            shutdown now
        fi
    fi
}

main "$@"
