#!/usr/bin/env bash

main () {
    if [[ $1 == 'auto' ]]; then
        sudo omen-fan-control fan-control --mode auto
    elif [[ $1 == 'curve' ]]; then
        sudo omen-fan-control fan-control --mode curve
    else
        sudo omen-fan-control fan-control --mode manual --value ${1}%
    fi
}

main "$@"
