#!/usr/bin/env bash

export DEV_ENV="/home/jaysh/dev"
source "${DEV_ENV}/lib/log"
source "${DEV_ENV}/lib/term-colors"
export -f log
export DRY_RUN='0'

main() {
    local recent_critical should_reboot
    should_reboot='n'
    paru

    # This looks at the pacman log for specific heavy-hitters
    recent_critical=$(grep -E "$(date +'%Y-%m-%d %H')" /var/log/pacman.log | \
                      grep -E "upgraded (glibc|systemd|dbus|wayland|hyprland)")

    # If /usr/lib/modules/$(uname -r) is missing, the kernel was upgraded.
    if [[ ! -d "/usr/lib/modules/$(uname -r)" ]]; then
        should_reboot='y'
        log "${WARN}[SYSTEM] Kernel has been updated. A reboot is REQUIRED.${RESET}"
    fi
    if [[ -n "$recent_critical" ]]; then
        should_reboot='y'
        log "${WARN}[SYSTEM] Critical system components (glibc/systemd) were updated.${RESET}"
        log "${INFO}It is highly recommended to reboot to ensure system stability.${RESET}"
    fi

    if [[ $should_reboot == 'n' ]]; then
        log "${INFO}[SYSTEM] System update completed successfully. Enjoy!${RESET}"
    fi
}

main "$@"
