#!/usr/bin/env bash
# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

export DEV_ENV="/home/jaysh/dev"
source "${DEV_ENV}/lib/log"
source "${DEV_ENV}/lib/ansi-escapes"
export -f log
export DRY_RUN='0'

main() {
    local recent_critical should_reboot
    should_reboot='n'
    paru

    # This looks at the pacman log for specific heavy-hitters
    recent_critical=$(grep -E "$(date +'%Y-%m-%d %H')" /var/log/pacman.log | \
                      grep -E "upgraded (glibc|systemd|dbus|wayland|hyprland)")

    # If /usr/lib/modules/$(uname -r) is missing, the kernel was upgraded.
    if [[ ! -d "/usr/lib/modules/$(uname -r)" ]]; then
        should_reboot='y'
        log "${WARN}[SYSTEM] Kernel has been updated. A reboot is REQUIRED.${RESET}"
    fi
    if [[ -n "$recent_critical" ]]; then
        should_reboot='y'
        log "${WARN}[SYSTEM] Critical system components (glibc/systemd) were updated.${RESET}"
        log "${INFO}It is highly recommended to reboot to ensure system stability.${RESET}"
    fi

    if [[ $should_reboot == 'n' ]]; then
        log "${INFO}[SYSTEM] System update completed successfully. Enjoy!${RESET}"
    fi
}

main "$@"
