#!/usr/bin/env bash
# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

export DEV_ENV="/home/jaysh/dev"
source "${DEV_ENV}/lib/log"
source "${DEV_ENV}/lib/ansi-escapes"
export -f logp
export DRY_RUN='0'

main() {
    local recent_critical should_reboot
    should_reboot='n'

    if ! sudo pacman -Syu; then
        logp 'SYS' "${ERR}Update failed! Please check the above log.${RESET}"
        return
    fi

    if ! paru; then
        logp 'SYS' "${ERR}Update failed! Please check the above log.${RESET}"
        return
    fi

    # this looks at the pacman log for specific heavy-hitters
    recent_critical=$(grep -F "[$(date +'%Y-%m-%dT')" /var/log/pacman.log |
        grep -E "upgraded (glibc|systemd|dbus|wayland|hyprland)")

    # if /usr/lib/modules/$(uname -r) is missing, the kernel was upgraded.
    if [[ ! -f "/usr/lib/modules/$(uname -r)/pkgbase" ]]; then
        should_reboot='y'
        logp 'SYS' "${WARN}The Kernel has been updated.${RESET}"
    fi
    if [[ -n "$recent_critical" ]]; then
        should_reboot='y'
        logp 'SYS' "${WARN}Critical system components were updated.${RESET}"
    fi
    if [[ $should_reboot == 'y' ]]; then
        logp 'SYS' "${WARN}It is highly recommended to reboot to ensure system stability.${RESET}"
    fi

    if [[ $should_reboot == 'n' ]]; then
        logp 'SYS' "${INFO}System update completed successfully. Enjoy!${RESET}"
    fi
}

main "$@"
