# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# tmp(!) alacritty config

[font]
normal.family = "JetBrainsMono NerdFont Mono"
normal.style = "ExtraLight"
size = 11

[window]
opacity = 0.2
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true
dimensions = { columns = 0, lines = 0 }

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[27;5;49~"

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[27;5;50~"

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[27;5;51~"

[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[27;5;52~"

[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[27;5;53~"

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

# tokyo-night-enhanced
[colors]
footer_bar = { foreground = "#787c99", background = "#08080b" }

[colors.primary]
background = "#08080b"
foreground = "#c0caf5"

[colors.cursor]
cursor = "#c0caf5"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
