# Copyright (C)  2026  Emir Baha YILDIRIM
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[ids]
*

[main]
# 1. Make CapsLock great again
# Holds -> Control, Taps -> Escape
capslock = overload(control, esc)
# 2. Move the actual CapsLock toggle to the physical Escape key
# Since you rarely need to shout, putting it in the corner is perfect.
esc = capslock

# 2. AltGr -> Super (For Hyprland)
# This prevents it from sending "Alt" and clashing with Tmux
altgr = layer(meta)
