#!/usr/bin/env bash

# Eraser Functions
export ERASE_AFTER_CURSOR='\033[0J' # Erases everything from the cursor to the end of the screen
export ERASE_BEFORE_CURSOR='\033[1J' # Erases everything from the cursor to the beginning of the screen
export ERASE_SCREEN='\033[2J' # Erases everything
export ERASE_LINE_AFTER_CURSOR='\033[0K' # Erases from cursor to the end of the line
export ERASE_LINE_BEFORE_CURSOR='\033[1K' # Erases from cursor to the beginning of the line
export ERASE_LINE='\033[2K' # Erases from cursor to the beginning of the line

# Cursor Visibility
export CURSOR_VISIBLE='\033[?25h'
export CURSOR_INVISIBLE='\033[?25l'

# Font Styles
export F_BOLD='\033[1m'
export F_DIM='\033[2m'
export F_ITALIC='\033[3m'
export F_ITALIC_RESET='\033[23m'
export F_UNDERLINE='\033[4m'
export F_UNDERLINE_RESET='\033[24m'
export F_STRIKE='\033[9m'
export F_STRIKE_RESET='\033[29m'

# Colors
export COLOR_RESET='\033[0m'
#    # Foreground Colors
#        # Light Colors
export FG_L_BLACK='\033[1;30m'
export FG_L_RED='\033[1;31m'
export FG_L_GREEN='\033[1;32m'
export FG_L_YELLOW='\033[1;33m'
export FG_L_BLUE='\033[1;34m'
export FG_L_MAGENTA='\033[1;35m'
export FG_L_CYAN='\033[1;36m'
export FG_L_WHITE='\033[1;37m'
export FG_L_DEFAULT_COLOR='\033[1;39m'
#        # Dark Colors
export FG_D_BLACK='\033[0;30m'
export FG_D_RED='\033[0;31m'
export FG_D_GREEN='\033[0;32m'
export FG_D_YELLOW='\033[0;33m'
export FG_D_BLUE='\033[0;34m'
export FG_D_MAGENTA='\033[0;35m'
export FG_D_CYAN='\033[0;36m'
export FG_D_WHITE='\033[0;37m'
export FG_D_DEFAULT_COLOR='\033[0;39m'
#    # Background Colors
#        # Light Colors
export BG_L_BLACK='\033[1;40m'
export BG_L_RED='\033[1;41m'
export BG_L_GREEN='\033[1;42m'
export BG_L_YELLOW='\033[1;43m'
export BG_L_BLUE='\033[1;44m'
export BG_L_MAGENTA='\033[1;45m'
export BG_L_CYAN='\033[1;46m'
export BG_L_WHITE='\033[1;47m'
export BG_L_DEFAULT_COLOR='\033[1;49m'
export BG_L_COLOR_RESET='\033[0m'
#        # Dark Colors
export BG_D_BLACK='\033[0;40m'
export BG_D_RED='\033[0;41m'
export BG_D_GREEN='\033[0;42m'
export BG_D_YELLOW='\033[0;43m'
export BG_D_BLUE='\033[0;44m'
export BG_D_MAGENTA='\033[0;45m'
export BG_D_CYAN='\033[0;46m'
export BG_D_WHITE='\033[0;47m'
export BG_D_DEFAULT_COLOR='\033[0;49m'
export BG_D_COLOR_RESET='\033[0m'

#   ERROR/INFO CODES FOR BACKWARDS COMPATIBILITY
export ERR='\033[0;31m'
export SUCC='\033[0;32m'
export WARN='\033[0;33m'
export INFO='\033[0;34m'
export RESET='\033[0m'

