#!/usr/bin/env bash

# # Created
# Author: Dave Eddy <ysap@daveeddy.com>
# Date: August 25, 2025
# License: MIT
#
# # Contributors
# - Dave Eddy <ysap@daveeddy.com>
# - Emir Baha Yıldırım <jayshozie@gmail.com>
#
# Original Source: <https://github.com/bahamas10/ysap/blob/6b585b69c3f7197432e61acec646e5e9aa2c47e8/code/2025-09-03-progress-bar-2/progress-bar>

BAR_CHAR='#'
EMPTY_CHAR=' '

clean_progress_bar() {
    printf '\e7'                         # save the cursor location
    printf '\e[%d;%dH' "$(tput lines)" 0 # move cursor to the bottom line
    printf '\e[0K'                       # clear the line
    printf '\e8'                         # restore the cursor location
}

progress_bar() {
    local current=$1
    local len=$2

    local perc_done=$((current * 100 / len))

    local suffix=" $current/$len ($perc_done%)"

    local length=$((COLUMNS - ${#suffix} - 2))
    local num_bars=$((perc_done * length / 100))

    local i
    local s='['
    for ((i = 0; i < num_bars; i++)); do
        s+=$BAR_CHAR
    done
    for ((i = num_bars; i < length; i++)); do
        s+=$EMPTY_CHAR
    done
    s+=']'
    s+=$suffix

    printf '\e7'                         # save the cursor location
    printf '\e[%d;%dH' "$(tput lines)" 0 # move cursor to the bottom line
    printf '\e[0K'                       # clear the line
    printf '%s' "$s"                     # print the progress bar
    printf '\e8'                         # restore the cursor location
}
