#!/usr/bin/env bash
# Dude, thanks you so much. That is probably the most elegant way of solving
# this I've seen. I spent hours trying to come up with a pure-bash way, but I
# couldn't do it without xxd etc.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 08, 2025
# License: MIT
# Usage: urlencode "string"
urlencode() {
    local LC_ALL=C
    for (( i = 0; i < ${#1}; i++ )); do
        : "${1:i:1}"
        case "$_" in
            [a-zA-Z0-9.~_-])
                printf '%s' "$_"
                ;;
            *)
                printf '%%%02X' "'$_"
                ;;
        esac
    done
}
