[Interface]
# Key for archomen
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 0F7jqDr6FKjwJmyuinpFHWLtdjIGye+hhU721VFEiH4=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#15
PublicKey = UIV6mDfDCun6PrjT7kFrpl02eEwqIa/piXoSKm1ybBU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.39.107.113:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a00:7c80:0:3ad::10]:51820
PersistentKeepalive = 25
