-- Copyright (C)  2026  Emir Baha YILDIRIM
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

return {
  -- { -- Copilot
  --     'github/copilot.vim',
  --     event = 'VeryLazy',
  --     config = function()
  --         vim.api.nvim_create_user_command('COPTOG', function()
  --                 local is_on = vim.b.copilot_enabled
  --                 if is_on or is_on == nil then
  --                     vim.cmd('Copilot disable')
  --                 else
  --                     vim.cmd('Copilot enable')
  --                 end
  --             end,
  --             { desc = 'Toggle Copilot' })
  --         vim.keymap.set('n', '<leader>c', vim.cmd('COPTOG'))
  --     end
  -- }
}
